### ISSUE TITLE
CSS missing img height

### ISSUE THREAD

**Issue by nicki-schinow** [sotastudio/TYPO3.Extbase.FlexSlider#27]
CSS needs to be like:

``` css
.flexslider .slides img {
        max-width: 100%;
        width: auto;
    height: auto;
}
```

Images are distorted.
